# values.yaml

replicaCount: 3

image:
  repository: dreamthre/nodagi_email
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 8080
  nodePort: 31163

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: ""
      paths:
        - path: /api/v1
          pathType: Prefix
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 100
  periodSeconds: 20
  timeoutSeconds: 10
  failureThreshold: 5
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 100
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 5
  successThreshold: 1

env:
  - name: "SPRING_DATASOURCE_URL"
    value: "jdbc:mysql://auth-mysql-email:3306/nodagi_email?serverTimezone=Asia/Seoul"
  - name: "SPRING_DATASOURCE_USERNAME"
    value: "root"
  - name: "SPRING_DATASOURCE_PASSWORD"
    value: "1234"
  - name: "SPRING_JPA_HIBERNATE_DDL_AUTO"
    value: "create"
  - name: "SPRING_JPA_DATABASE_PLATFORM"
    value: "org.hibernate.dialect.MySQLDialect"
  - name: "redis"
    value: "auth-redis"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
